from .exception import (
    VitapVtopClientError,
    VtopConnectionError,
    VtopCaptchaError,
    VtopCaptchaSolvingError,
    VtopCsrfError,
    VtopLoginError,
    VtopLoginOtpRequiredError,
    VtopLoginOtpIncorrectError,
    VtopLoginOtpExpiredError,
    VtopSessionError,
    VtopParsingError,
    VtopAttendanceError,
    VtopBiometricError,
    VtopTimetableError,
    VtopMentorError,
    VtopGradeHistoryError,
    VtopProfileError
)